### ISSUE TITLE
How to Identify an element with Regex

### ISSUE THREAD

**Issue by Pramanth** [northwoodspd/uia#10]
Is there a way in UIA to find an element with regular expression. I know we can use regex to find Window like "/window_name/i"

**Comment by leviwilson** [comment]
The [`uia_spec`](https://github.com/northwoodspd/uia/blob/eafe3dd5f27cbc5b3c73a9c9342af234f6e5f309/spec/uia_spec.rb) has some examples of finding things by regex.

Note that when you are looking for things by regex that have to go down into UI Automation that they won't be as fast as if you use locators that use win32 calls, like window title, etc.

**Comment by Pramanth** [comment]
Thanks @leviwilson for the information.

Tried different ways like Uia.children.find { |e| e.name =~ /MainFormWindow/ } etc., but could not able to find a way to identify the children with partial match. For now we are getting all the children under a element and returning the element name based on the regex match .

**Comment by leviwilson** [comment]
It'd likely be beneficial to know the structure of your app (as seen by UI Spy) to have a better recommendation.

In _general_, however...you want to refrain from doing a lot of regex searches within a `.children` (top-level children only) and **especially** with a `.descendants` since that can be CPU intensive as it is not a fast operation to hit that may UIA calls in your entire window structure.

You really want to be leveraging the automation IDs where possible since those are the fastest lookups.

**Comment by Pramanth** [comment]
@leviwilson  Sorry for the delay. Below is the way the application is structured in UI Spy,

<img width="1297" alt="image" src="https://cloud.githubusercontent.com/assets/5500683/21450553/3ddc7d20-c91e-11e6-8b19-9aa0bbf6d636.png">

We want to interact with attachments and we have file name to interact with the element not the size of the file.

Got your valuable points wrt drawback of regex search. Thank you.

**Comment by leviwilson** [comment]
Gotcha; I have another gem that is a higher-level wrapper around `uia`. It's called [`mohawk`](https://github.com/leviwilson/mohawk). It _looks_ like you have a root for your list in "Attachments" up there; my guess is that it has an `AutomationId` for it? If so, you could define a page object like so:

```ruby
class SomeScreen
  include Mohawk
  window(title: /RegEx for some top-level window/)

  select_list(:attachment, id: 'runtimeIdForAttachments')
end
```

Then you can interact with it like so:

```ruby
on(SomeScreen) do |screen|
  screen.attachment = 'sk2.jpg.html'
end
```

I _believe_ you can pass a regex in as well, so `on(SomeScreen).attachment = /^sk2/`.

**Comment by Pramanth** [comment]
Thanks @leviwilson for all the information.
