### ISSUE TITLE
Error You must install the Visual Studio 2012 C++ Runtime Environment

### ISSUE THREAD

**Issue by janiskragis** [northwoodspd/uia#13]
Not so far ago I updated ruby to 2.5.1p57, I think that was the point when UIA gem stopped workong, now I get error:
gems/2.5.0/gems/uia-0.6/lib/uia/library.rb:202:in `rescue in <module:Library>': You must install the Visual Studio 2012 C++ Runtime Environment to use the Uia gem (http://www.microsoft.com/en-us/download/details.aspx?id=30679) (LoadError)
I do have "Visual Studio 2012 C++ Runtime Environment" installed. Any Ideas ?
Thanks in advance.
Janis

**Comment by janiskragis** [comment]
Not sure if Ruby version is to blame. I installed URU to switch to older versions and I get the same error, but I can’t think of any other changes I made to my system since the last time I was running script that using uia gem and it worked fine.

**Comment by janiskragis** [comment]
Solved the problem myself, I had ruby version 2.5.1p57 - x64, so I installed 2.5.1p57 - x86 in different directory, used uru to switch to x86 version, installed gems I need and now the script is running fine.

**Comment by leviwilson** [comment]
Yep, the gem is intended for x86 ruby.

There's an x64 branch that I'm not sure is entirely there yet if you want to try it. It's been a bit since I've looked at it.
