### ISSUE TITLE
Uia gem will support Ruby 2.6.5x 64bit version

### ISSUE THREAD

**Issue by radhakrishnanakireddy** [northwoodspd/uia#17]
Hi,
I am trying to use uia gem with ruby 2.6.5 64bit,  I had gone the through the issues list, but requesting solution  one more time for this issue if available.

Could anyone please help me regarding this :-)

**Comment by leviwilson** [comment]
Unfortunately I haven't been actively working on this project. A couple of years ago, however, I took a stab at allowing for 64-bit calls in [this branch](https://github.com/northwoodspd/uia/tree/x64).

You can specify this branch in your `Gemfile` and see if you have any luck.
